name: Release

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  macos:
    runs-on: macos-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4

      - name: Generate access token
        uses: Roblox-ActionsCache/tibdex-github-app-token@v1.4.0
        id: setup_token
        with:
          app_id: ${{ secrets.TOKENS_APP_LUA_ECOSYSTEM_DEPENDENCIES_ID }}
          private_key: ${{ secrets.TOKENS_APP_LUA_ECOSYSTEM_DEPENDENCIES_KEY }}

      - name: Get foreman and run foreman install
        uses: Roblox/setup-foreman@v3
        with:
          version: "^1.0.0"
          token: ${{ steps.setup_token.outputs.token }}
          allow-external-github-orgs: true

      - name: Build release artifacts
        run: |
          lute scripts/build

      - uses: actions/upload-artifact@v5
        with:
          name: rocale-cli-macos-x86_64
          path: build/rocale-cli

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4

      - name: Generate access token
        uses: Roblox-ActionsCache/tibdex-github-app-token@v1.4.0
        id: setup_token
        with:
          app_id: ${{ secrets.TOKENS_APP_LUA_ECOSYSTEM_DEPENDENCIES_ID }}
          private_key: ${{ secrets.TOKENS_APP_LUA_ECOSYSTEM_DEPENDENCIES_KEY }}

      - name: Get foreman and run foreman install
        uses: Roblox/setup-foreman@v3
        with:
          version: "^1.0.0"
          token: ${{ steps.setup_token.outputs.token }}
          allow-external-github-orgs: true

      - name: Build release artifacts
        run: |
          lute scripts/build

      - uses: actions/upload-artifact@v5
        with:
          name: rocale-cli-linux-x86_64
          path: build/rocale-cli

  windows:
    runs-on: windows-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4

      - name: Generate access token
        uses: Roblox-ActionsCache/tibdex-github-app-token@v1.4.0
        id: setup_token
        with:
          app_id: ${{ secrets.TOKENS_APP_LUA_ECOSYSTEM_DEPENDENCIES_ID }}
          private_key: ${{ secrets.TOKENS_APP_LUA_ECOSYSTEM_DEPENDENCIES_KEY }}

      - name: Get foreman and run foreman install
        uses: Roblox/setup-foreman@v3
        with:
          version: "^1.0.0"
          token: ${{ steps.setup_token.outputs.token }}
          allow-external-github-orgs: true

      - name: Build release artifacts
        run: |
          lute scripts/build

      - uses: actions/upload-artifact@v5
        with:
          name: rocale-cli-windows-x86_64.exe
          path: build/rocale-cli.exe
